### PR TITLE
Secret key value pair selection

### PR DESCRIPTION
**Pull request by synax**
Hi.

thank you for implementing this provider, I think summon is an awesome tool. I've added some functionality because we use key-value pairs and one secret per environment application. I thought it would be neat if we could declare the key directly via summon. Would be cool if we could integrate this. 

Thanks Stefan

### CODE REVIEW

**Comment by synax** [comment]
Ups, I just noticed that this is a duplicate. :) Looking forward to the next release then. sorry

**Comment by sgnn7** [comment]
Hey @synax, thanks for your contribution and I think you might have closed this PR a bit prematurely! :)

Your PR has the golang modules change which is really nice and has a bit of a cleaner approach than the original PR. If you could take the same syntax from there (`#` vs `:`) and whatever else is on it (e.g. docs), I think this PR might take precedence. Let me know what you think!

**Comment by doodlesbykumbi** [comment]
@synax I wrote the original PR and I second the comments above. Also, I think having accessing to arbitrarily nested values would be nice but I'm no longer sure if gjson is the way to go.

**Comment by synax** [comment]
Hey, sorry for the delayed response, I agree. We are currently using my pr in our development environment. Would be great if we could integrate it in to the next release. I think I should have time next week to finish this off. I'll change the `:` char to `#` and add it to the commit. I`ll also merge the documentation added by @doodlesbykumbi with mine. @sgnn7 Anything else you would like me to change/add in this PR to get it merged?

**Comment by sgnn7** [comment]
@synax Awesome! I think that's all that's needed and if something changes on our end, we will update the comments here. 👍

**Comment by synax** [comment]
So, this should now implement #6 and should be ready to be merged.

**Comment by sgnn7** [comment]
@synax Great work! It seems like we will need a few more changes on the pipeline to make this work so we will use this branch as a base for another PR that includes the full changes needed (I'll update this thread with the new PR).

Thanks again!

**Comment by sgnn7** [comment]
Closing this PR since https://github.com/cyberark/summon-aws-secrets/pull/10 supersedes it

**Pull request closed without merging**
